### ISSUE TITLE
support for overriding default config

### ISSUE THREAD

**Issue by codekidX** [oksketch/sketch#5]
`default.toml` must be the common config from which all the other config can be extended.

eg:
default
```toml
port = ":4000"
name = "app"
```
alpha
```toml
port = ":7000"
```

for `SKETCH_ENV` alpha it final config must be
```toml
port = ":7000"
name = "app"
```
